# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MiniChat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eMiniChat.proto\"\'\n\x06Object\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06socket\x18\x02 \x01(\t\"%\n\x05Reply\x12\x0c\n\x04\x66lag\x18\x01 \x01(\x08\x12\x0e\n\x06socket\x18\x02 \x03(\t\"\x1e\n\x0b\x63hatMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x0eversionMessage\x12\x0f\n\x07version\x18\x01 \x01(\x05\x32\xa4\x01\n\x07Routing\x12\x19\n\x04\x46ind\x12\x07.Object\x1a\x06.Reply\"\x00\x12\x1e\n\tuserLogin\x12\x07.Object\x1a\x06.Reply\"\x00\x12\x1f\n\nuserLogout\x12\x07.Object\x1a\x06.Reply\"\x00\x12\x1d\n\x08joinRoom\x12\x07.Object\x1a\x06.Reply\"\x00\x12\x1e\n\tleaveRoom\x12\x07.Object\x1a\x06.Reply\"\x00\x32\xaa\x02\n\x04\x63hat\x12#\n\tsend_room\x12\x0c.chatMessage\x1a\x06.Reply\"\x00\x12\x31\n\x16\x61pply_for_room_history\x12\x07.Object\x1a\x0c.chatMessage\"\x00\x12\x32\n\x14request_room_version\x12\x07.Object\x1a\x0f.versionMessage\"\x00\x12\'\n\rsend_personal\x12\x0c.chatMessage\x1a\x06.Reply\"\x00\x12\x35\n\x1a\x61pply_for_personal_history\x12\x07.Object\x1a\x0c.chatMessage\"\x00\x12\x36\n\x18request_personal_version\x12\x07.Object\x1a\x0f.versionMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MiniChat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_OBJECT']._serialized_start=18
  _globals['_OBJECT']._serialized_end=57
  _globals['_REPLY']._serialized_start=59
  _globals['_REPLY']._serialized_end=96
  _globals['_CHATMESSAGE']._serialized_start=98
  _globals['_CHATMESSAGE']._serialized_end=128
  _globals['_VERSIONMESSAGE']._serialized_start=130
  _globals['_VERSIONMESSAGE']._serialized_end=163
  _globals['_ROUTING']._serialized_start=166
  _globals['_ROUTING']._serialized_end=330
  _globals['_CHAT']._serialized_start=333
  _globals['_CHAT']._serialized_end=631
# @@protoc_insertion_point(module_scope)
